services:
  postgres:
    image: postgres:17-alpine
    container_name: pyetimes_postgres
    environment:
      POSTGRES_DB: pyetimes_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - pyetimes_network

volumes:
  postgres_data:

networks:
  pyetimes_network:
    driver: bridge